### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SigmaDee** [RAGUL1902/Dynamic-Memory-Allocation-in-C#1]
Hey!
I was wondering what license you consider this code to be under. Is it free to grab and modify without restrictions?
I understand it is based on Dan Luu's tutorial, right?

Thanks!

**Comment by RAGUL1902** [comment]
Hi,

Thank you for reaching out to me. I have added MIT License.
Yes, it is based on Dan Luu's tutorial which I have added in the readme.

**Comment by SigmaDee** [comment]
Thanks!
